apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vote-app-back-end
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vote-app
        component: back-end
    spec:
      containers:
      - name: back-end
        image: bkedjour/vote-app-backend:0.8
        env:
        - name: ConnectionString
          value:  vote-app-data
        ports:
        - containerPort: 80
