apiVersion: v1
kind: Service
metadata:
  name: vote-app-front-end
  labels:
    app: vote-pp
    component: front-end
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: vote-app
    component: front-end