apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vote-app-front-end
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vote-app
        component: front-end
    spec:
      containers:
      - name: front-end
        image: bkedjour/vote-app-front:0.8
        env:
        - name: BackendConnectionString
          value:  vote-app-back-end
        ports:
        - containerPort: 80